// <auto-generated />
namespace Practica_semanal2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Generos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Generos));
        
        string IMigrationMetadata.Id
        {
            get { return "202005240209215_Generos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
